name: From source(Windows)

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - '.github/workflows/test-src-build-windows.yml'
      - 'third-party/**'
      - 'setup.*'
      - 'pyproject.toml'
      - 'src/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-src-build-windows.yml'
      - 'third-party/**'
      - 'setup.*'
      - 'pyproject.toml'
      - 'src/**'

concurrency:
  group: src_windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows_2019:
    name: Windows:2019-x86_64
    runs-on: windows-2019
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: MINGW64
      CHERE_INVOKING: 1
      MSYS2_PREFIX: "C:/msys64/mingw64"

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - name: Set up shellBuild
        run: echo "C:\msys64\usr\bin\" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Install base packages
        run: |
          pacman -S --noconfirm \
            mingw-w64-x86_64-gcc \
            mingw-w64-x86_64-python3-pip \
            mingw-w64-x86_64-python3-setuptools \
            mingw-w64-x86_64-binutils

#      - name: Build x265 and dependencies
#        run: |
#          cd third-party/x265/windows/mingw-w64-x265
#          makepkg-mingw --syncdeps --noconfirm -f
#          pacman -U mingw-w64-x86_64-x265-*-any.pkg.tar.zst --noconfirm

      - name: Build x265 and dependencies
        run: pacman -S --noconfirm mingw-w64-x86_64-x265

      - name: Build libheif and dependencies
        run: |
          cd tests
          makepkg-mingw --syncdeps --noconfirm -f
          pacman -U mingw-w64-x86_64-libheif-*-any.pkg.tar.zst --noconfirm

      - name: Installing Pillow-Heif-x265
        run: SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pip -v install ".[tests]"

      - name: Install Pillow-Heif
        run: python3 -m pip install git+https://github.com/bigcat88/pillow_heif.git

      - name: Perform tests
        run: python3 ./tests/temporary.py
