name: From source(Windows)

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - '.github/workflows/test-src-build-windows.yml'
      - 'third-party/**'
      - 'setup.*'
      - 'pyproject.toml'
      - 'src/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-src-build-windows.yml'
      - 'third-party/**'
      - 'setup.*'
      - 'pyproject.toml'
      - 'src/**'

concurrency:
  group: src_windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows_2019:
    name: Windows:2019-x86_64
    runs-on: windows-2019
    env:
      MSYS2_PREFIX: "C:/temp/msys64/mingw64"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: msys2/setup-msys2@v2
        with:
          location: C:/temp
          install: >-
            mingw-w64-x86_64-binutils

      - name: Build x265 and dependencies
        shell: msys2 {0}
        run: |
          cd libheif/windows/mingw-w64-x265
          makepkg-mingw --syncdeps --noconfirm -f
          pacman -U mingw-w64-x86_64-x265-*-any.pkg.tar.zst --noconfirm

      - name: Installing Pillow-Heif-x265
        run: python -m pip -v install ".[tests]"

      - name: Build libheif and dependencies
        shell: msys2 {0}
        run: |
          cd tests
          makepkg-mingw --syncdeps --noconfirm -f
          pacman -U mingw-w64-x86_64-libheif-*-any.pkg.tar.zst --noconfirm

      - name: Copy DLLs from MSYS2
        run: |
          $site_packages=(python -c 'import sysconfig; print(sysconfig.get_paths()["platlib"])')
          cp ${{ env.MSYS2_PREFIX }}/bin/libheif.dll $site_packages/
          cp ${{ env.MSYS2_PREFIX }}/bin/libde265-0.dll $site_packages/
          cp ${{ env.MSYS2_PREFIX }}/bin/libx265.dll $site_packages/
          cp ${{ env.MSYS2_PREFIX }}/bin/libwinpthread-1.dll $site_packages/
          cp ${{ env.MSYS2_PREFIX }}/bin/libgcc_s_seh-1.dll $site_packages/
          cp ${{ env.MSYS2_PREFIX }}/bin/libstdc++-6.dll $site_packages/

      - name: Install Pillow-Heif
        run: python3 -m pip install git+https://github.com/bigcat88/pillow_heif.git

      - name: Perform tests
        run: python3 ./tests/temporary.py
